import './globals.css'
import React from 'react'
import SideMenu from './components/SideMenu'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className='bg-slate-200'>
      <body className='flex bg-slate-200'>
        <SideMenu />
        {children}
      </body>
    </html>
  )
}
